### PR TITLE
Physics demo: colliders, joints, hand interaction

### PR DESCRIPTION
**Pull request by jmiskovic**

### CODE REVIEW

**Comment by bjornbytes** [comment]
These are great!  I do want to make one change to the way they are grouped/categorized, but there are 2 ways to go about it.  I'll let you pick based on how you want things to be presented.

- Examples: If the focus is on showing people how to quickly create different types of joints/objects, I think it would be useful if each one was a single example.  That way people can browse through a sidebar category that has specific items like "Saloon Door", "Rope", "Newton's Cradle", etc. instead of a single nebulous "Joints" recipe.
- Showcase: If the focus on being more of a playground showcasing what's possible with the physics system, then having them all in one project makes more sense, but I'd want to move it into the "Showcase" section.

Context: In the next release I'm going to be renaming the "examples" to "recipes", and I've added the hierarchical folder system in preparation for that.  The goal is to have the Recipes section be lots of small specific examples focused on the code, and the Showcase section to be higher level projects more focused on the end result.

(One problem with having lots of recipes is the issue of code sharing, but I plan on tackling that once it becomes a problem, and I think having *some* repetition is preferable to hiding the boilerplate from readers).

**Comment by jmiskovic** [comment]
I can make few smaller and more focused examples:
* hand interaction - pushing, grabbing, throwing
* instantiating and drawing all collider types
* each joint type in its own example

Only hand interaction example would be interactive, and there would be no code sharing between examples.

**Comment by jmiskovic** [comment]
There. Some of those are much shorter and more focused. Hand interaction and collider rendering are over 100 LoC, but they should be more useful than rest of demos. I dropped the springy icosphere as it's no fun without hands.

**Comment by bjornbytes** [comment]
Awesome!  It's cool to finally have some good physics examples

**Pull request merged**
