### PR TITLE
Fix swapped name and type in `getDirectoryItems.lua`

### PR DESCRIPTION
**Pull request by pterror**
not 100% sure about this one, but this is the only entry with a weird type

### CODE REVIEW

**Comment by bjornbytes** [comment]
Looks good to me.  Thanks for the fix!

**Comment by pterror** [comment]
oops... i found another issue that seems to have accidentally gotten merged. i *think* it's correct, but it's probably best to let you know just as a heads up

**Comment by bjornbytes** [comment]
I saw that one too, looks good as well.  This gave me the idea to validate the types better in api/main.lua (make sure they're either a valid Lua type, or an enum type, or some other special syntax like `*`), and warn if there are any issues.  That way this type of issue won't happen again.  I'll try to do this soon.

**Comment by pterror** [comment]
hmm, seems like there's another of the same typo in: https://github.com/bjornbytes/lovr-docs/blob/ec6c36e39ad3827aa2bcf0a49ade5eef041d7f3b/api/init.lua#L12443

**Comment by bjornbytes** [comment]
Yeah, the docs need to be regenerated after the source pages have changed... I can do that now

**Comment by bjornbytes** [comment]
Ok regenerated dev, and applied these 2 fixes to v0.17.0 as well so it should show up on the website

**Comment by bjornbytes** [comment]
Ok I updated the generator to validate argument/return types better.  This didn't uncover any new issues, so you caught the 2 remaining problems!

**Pull request merged**
